In [27]:
import pandas as pd
import matplotlib.pyplot as plt
data= pd.read_csv('ex1data2.txt',usecols=[0,1,2],header=None)
df = pd.DataFrame(data)
#number of features
n = 2
i = 0
mean = []
sd = []
while i <n:
    mean.append(df[i].mean())
    sd.append(df[i].std())
    df[i] = df[i]-mean[i]
    df[i] = df[i]/sd[i]
    i += 1







[[ 1.00000000e+00  1.30009869e-01 -2.23675187e-01]
 [ 1.00000000e+00 -5.04189838e-01 -2.23675187e-01]
 [ 1.00000000e+00  5.02476364e-01 -2.23675187e-01]
 [ 1.00000000e+00 -7.35723065e-01 -1.53776691e+00]
 [ 1.00000000e+00  1.25747602e+00  1.09041654e+00]
 [ 1.00000000e+00 -1.97317285e-02  1.09041654e+00]
 [ 1.00000000e+00 -5.87239800e-01 -2.23675187e-01]
 [ 1.00000000e+00 -7.21881404e-01 -2.23675187e-01]
 [ 1.00000000e+00 -7.81023044e-01 -2.23675187e-01]
 [ 1.00000000e+00 -6.37573110e-01 -2.23675187e-01]
 [ 1.00000000e+00 -7.63567023e-02  1.09041654e+00]
 [ 1.00000000e+00 -8.56737193e-04 -2.23675187e-01]
 [ 1.00000000e+00 -1.39273340e-01 -2.23675187e-01]
 [ 1.00000000e+00  3.11729182e+00  2.40450826e+00]
 [ 1.00000000e+00 -9.21956312e-01 -2.23675187e-01]
 [ 1.00000000e+00  3.76643089e-01  1.09041654e+00]
 [ 1.00000000e+00 -8.56523009e-01 -1.53776691e+00]
 [ 1.00000000e+00 -9.62222960e-01 -2.23675187e-01]
 [ 1.00000000e+00  7.65467909e-01  1.09041654e+00]
 [ 1.00000000e+00  1.29648433e+

In [50]:
#cost calculation function
import numpy as np
#cost calculation for single iteration
height = len(df[0])
width = 1
d = pd.DataFrame(1 ,index=range(height), columns=range(width))
newdf = [d[0],df[0], df[1]].copy()
newdf = pd.concat(newdf,axis=1)
newdf=newdf.values


def calculate_cost(y,features,weights):
    n=len(weights)
    cost=0
    for x,y in zip(features,y):
        y_pred = np.dot(np.array([x]),weights)
        cost=(y_pred - y)**2
    cost = cost / (2*len(df[0]))
    return cost
calculate_cost(df[2],newdf,np.array([1,1,1]))



array([6.10216584e+08])

In [63]:
#gradient descent 
def batch_gradient_descent(features,out, weights, trate, iter_count):
    iteration = 0
    while iteration <iter_count:
        err=np.array([0])
        #err=np.reshape(err,(iter_count))
        gradient=0
        gradient2=0
        gradient3=0
        g=np.array([0])       #to save sums of gradient at each iteration
        for x,y in zip(features,out):
            y_hat = np.dot(np.array([x]),weights)
            diff=y-y_hat
            #for weight 1
            gradient=gradient+x[0]*diff
            #for weight 2
            gradient2=gradient+x[1]*diff
            #for weight3
            gradient3=gradient+x[2]*diff
            
        weights[0] = weights[0] - ((trate * gradient)/len(newdf[0]))
        weights[1] = weights[1] - ((trate * gradient2)/len(newdf[0]))
        weights[2] = weights[2] - ((trate * gradient3)/len(newdf[0]))
            
        #print(weights[0])
        #print(weights[1])
        #print(weights[2])
        #print("Error:")
        
        err=np.append(err,calculate_cost(df[2],newdf,weights))
        print(err)
        iteration=iteration+1
        
    print(err)
        

        
        
    
            #print(gradient)
        
            
           
   
            
        
            
        
        
    
batch_gradient_descent(newdf,df[2],np.array([1,1,1],dtype=np.float64),0.003,50)




[0.00000000e+00 5.93087656e+08]
[0.00000000e+00 5.75338351e+08]
[0.00000000e+00 5.56968312e+08]
[0.00000000e+00 5.37980023e+08]
[0.0000000e+00 5.1837922e+08]
[0.00000000e+00 4.98175352e+08]
[0.00000000e+00 4.77382083e+08]
[0.00000000e+00 4.56017866e+08]
[0.00000000e+00 4.34106562e+08]
[0.00000000e+00 4.11678142e+08]
[0.00000000e+00 3.88769454e+08]
[0.00000000e+00 3.65425081e+08]
[0.00000000e+00 3.41698281e+08]
[0.00000000e+00 3.17652038e+08]
[0.00000000e+00 2.93360217e+08]
[0.00000000e+00 2.68908842e+08]
[0.00000000e+00 2.44397509e+08]
[0.00000000e+00 2.19940951e+08]
[0.00000000e+00 1.95670753e+08]
[0.00000000e+00 1.71737262e+08]
[0.00000000e+00 1.48311679e+08]
[0.00000000e+00 1.25588379e+08]
[0.00000000e+00 1.03787454e+08]
[       0.         83157535.57742171]
[       0.         63978886.71348382]
[       0.         46566819.91933777]
[       0.       31275457.307971]
[       0.         18501872.23586638]
[      0.         8690648.91074319]
[      0.         2338901.23147808]
[   0.  

In [23]:
for x,y in zip(newdf,df[2]):
            y_hat = np.dot(np.array([x]),np.array([1,1,1],dtype=np.float64))
            print(y_hat)
            

[0.90633468]
[0.27213497]
[1.27880118]
[-1.27348998]
[3.34789255]
[2.07068481]
[0.18908501]
[0.05444341]
[-0.00469823]
[0.1387517]
[2.01405984]
[0.77546808]
[0.63705147]
[6.52180009]
[-0.1456315]
[2.46705963]
[-1.39428992]
[-0.18589815]
[2.85588445]
[3.38690087]
[0.48227654]
[-0.67955692]
[0.27716831]
[2.04174316]
[3.15371698]
[-0.3570314]
[0.09345172]
[1.4373511]
[1.02713463]
[1.57702604]
[-0.74121522]
[-3.11104813]
[2.13989311]
[2.20619242]
[1.85173491]
[0.06702674]
[-0.18212315]
[2.25565972]
[4.87676685]
[2.29340971]
[-0.96142345]
[1.07495127]
[2.80303447]
[-0.23119813]
[-1.98318965]
[1.90332655]
[-0.22742313]
